# Generated by Django 4.2.17 on 2024-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
